### PR TITLE
Adding 36 UCD manual annotations 

### PR DESCRIPTION
**Pull request by callahantiff**
Adding the first 36 LOINC annotations from the UCDenver LOINC2HPO survey.

### CODE REVIEW

**Comment by kingmanzhang** [comment]
Hi Tiffany, 

Thank you for creating the pull request. I just looked at it through your fork (somehow GitHub thinks the changes are too large to show). I think they mostly look good. I would suggest you think about annotating normal findings in your commit. We have annotated a normal finding as NOT ${HPO term}. In most cases, this HPO term is the parent of terms used to annotated abnormal findings. For example, an normal finding in blood potassium concentration is NOT Abnormality of blood potassium homeostasis, which is the parent of Hyperkalemia and Hypokalemia.

Another minor suggestion is that please create pull request to merge to develop branch. This will make it easier for us to qc and release periodically. 

Please let me know if a call is needed.

**Comment by callahantiff** [comment]
Hi Aaron-

Thank you very much for the update and for verifying the annotations. 

Great suggestion for normal lab results; I can add the annotations for this result type to all annotated LOINC terms following the procedure that you described. 

I will also submit the next pull request to the development branch, sorry about that!

I can try submitting the next batch as a single commit, instead of separate commits for each lab test. Perhaps that is a contributing factor to you not being able to view the changes? I’m not sure that logic is sound, but if you don’t mind and it doesn’t affect your workflow, then I can give it a try?

I will work on these changes as well as submitting the next batch later today and throughout the end of the weekend.


-Tiffany

**Comment by kingmanzhang** [comment]
Sounds good! I do not think it is necessary to create a commit for every LOINC. But it is a personal style. I am not sure why Github says "+1 −5,749" for file changes as it basically means you added one line but deleted 5749 lines from our master branch, but that is the reason why it chose not render the changes. But we will be able to figure out and merge your changes.

**Comment by kingmanzhang** [comment]
So I guess I will skip this pull request and wait for additions (for normal findings).

**Comment by callahantiff** [comment]
Thanks Aaron, waiting to accept the pull request until I add the normal lab results makes sense. I’ve set aside time to work on this tomorrow.

**Comment by callahantiff** [comment]
Closing this pull request. I will submit a new pull request to the develop branch with all of the annotations (including annotations to normal results).

**Pull request closed without merging**
